gText_NurseJoy_Welcome:: @ 81A0A7D
	.string "Hello, and welcome to the POKéMON\n"
	.string "CENTER.\p"
	.string "We restore your tired POKéMON to\n"
	.string "full health.\p"
	.string "Would you like to rest your POKéMON?$"

gText_NurseJoy_Fainted:: @ 81A0A00
	.string "Your POKéMON {STR_VAR_1} has fainted.\n"
	.string "They must be stored or released.\p$"

gText_NurseJoy_Store:: @ 81A0A00
	.string "Store {STR_VAR_1}?$"

gText_NurseJoy_StoreCompleted:: @ 81A0A00
	.string "{STR_VAR_1} has been stored\n"
	.string "in the PC.\p"
	.string "They can no longer battle.\p$"

gText_NurseJoy_Release:: @ 81A0A00
	.string "Release {STR_VAR_1}?$"

gText_NurseJoy_ReleaseCompleted:: @ 81A0A00
	.string "{STR_VAR_1} has been released.\p$"

gText_NurseJoy_WeHopeToSeeYouAgain:: @ 81A0AFA
	.string "We hope to see you again!$"

gText_NurseJoy_ThankYouForWaiting:: @ 81A0B14
	.string "Thank you for waiting.\p"
	.string "We've restored your POKéMON to\n"
	.string "full health.$"

UnknownString_81A0B57: @ 81A0B57
	.string "Welcome to the POKéMON CABLE CLUB\n"
	.string "TRADE CENTER.$"

UnknownString_81A0B87: @ 81A0B87
	.string "Welcome to the POKéMON CABLE CLUB\n"
	.string "COLOSSEUM.$"

UnknownString_81A0BB4: @ 81A0BB4
	.string "Welcome to the POKéMON CABLE CLUB\n"
	.string "TIME CAPSULE.$"
